load_data:
  file: "news_995k.csv"
  usecols: ["id", "domain", "type", "url", "content", "title"]
clean_data:
  lower: true
  collapse_whitespace: true
  regexes:
    '[a-zA-Z]+.?\s*\d{1,2}[,.]?\s*\d{4}': "<DATE>"
    '[\w.]+@[\w.]+': "<EMAIL>"
    '([^\W\d]*)://(((\w*@)?([\w-]+(\.[\w-]+)+)(:[\d]+)?))?(/[\w-]+)*\/?(?:\?[^\s#]*)?(#[\w-]+)?': "<URL>"
    '\d[\d.,]*': "<NUM>"
save_data:
  filename: "news_995k_cleaned.csv"