load_data:
  file: "995,000_rows.csv"
clean_data:
  lower: true
  collapse_whitespace: true
  regexes:
    '[a-zA-Z]+.?\s*\d{1,2}[,.]?\s*\d{4}': "<DATE>"
    '[\w.]+@[\w.]+': "<EMAIL>"
    '([^\W\d]*)://(((\w*@)?([\w-]+(\.[\w-]+)+)(:[\d]+)?))?(/[\w-]+)*\/?(?:\?[^\s#]*)?(#[\w-]+)?': "<URL>"
    '\d[\d.,]*': "<NUM>"
save_data:
  filename: "full_dataset_cleaned.csv"